# Generated by Django 4.1.1 on 2022-10-28 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_review_options_remove_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
