# Generated by Django 4.1.1 on 2022-10-31 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hike',
            new_name='hikes',
        ),
    ]
